import type { JsonObject } from "./json.ts";
import { createOperatorFileReader, diskIo, type OperatorFileIo } from "./operator-file.ts";

// "Plain" / "lost" retellings of a Claude session for the phone, generated by the operator's own
// cc-sidecar-waitwhat (`ww`) so the prompts, the turn selection and the answer cache stay the ones
// the terminal and the in-Claude mod already share — Collie writes no prompt of its own.
//
// This is the second exception to "the bridge spawns no child for content" (ADR 0074): it exists
// only while the operator's `retell.toml` names a command, and each request is ONE short-lived child
// with a fixed argv — never a shell, never a daemon, never an argument the phone chose. The phone
// names a pane and one of two modes; the bridge maps the pane to the session id the multiplexer
// reported and adds that id as the child's `--session-id`.

export type RetellMode = "plain" | "lost";

/** The operator's `retell.toml`, parsed. */
export interface RetellConfig {
  /** argv prefix, e.g. `["/Users/me/.local/bin/ww", "--source", "http"]`. */
  readonly command: readonly string[];
}

/**
 * ```toml
 * command = ["/Users/me/.local/bin/ww", "--source", "http"]
 * ```
 *
 * An array, not a shell line: nothing is ever split or interpreted, so no character in it needs
 * escaping and none can smuggle a second command. Returns zero rows or one.
 */
export function validateRetellConfig(
  doc: { command?: unknown } | null | undefined,
  warn = defaultWarn,
): RetellConfig[] {
  const command = doc?.command;
  if (command === undefined || command === null) return [];
  if (!Array.isArray(command) || command.length === 0) {
    warn("`command` must be a non-empty array of strings — retell stays off");
    return [];
  }
  const argv: string[] = [];
  for (const part of command) {
    if (typeof part !== "string" || part === "" || part.includes("\0")) {
      warn("`command` holds a value that is not a non-empty string — retell stays off");
      return [];
    }
    argv.push(part);
  }
  return [{ command: argv }];
}

function defaultWarn(message: string): void {
  console.warn(`[retell] ${message}`);
}

export function createOperatorRetell(
  path: string,
  io: OperatorFileIo = diskIo,
  warn = defaultWarn,
): () => Promise<RetellConfig[]> {
  return createOperatorFileReader(path, validateRetellConfig, io, warn);
}

/** The child's argv for one request. The session id is the multiplexer's, never the client's. */
export function retellArgv(config: RetellConfig, mode: RetellMode, sessionId: string, fresh: boolean): string[] {
  return [
    ...config.command,
    ...(mode === "plain" ? ["1"] : []),
    "--session-id",
    sessionId,
    "--json",
    ...(fresh ? ["--no-cache"] : []),
  ];
}

export type RetellResult =
  | {
      readonly ok: true;
      readonly sessionId: string;
      readonly mode: RetellMode;
      readonly label: string;
      readonly answer: string;
      readonly cached: boolean;
      readonly source: string;
    }
  | { readonly ok: false; readonly error: string };

/**
 * The child's stdout, believed only as far as it checks out. A body that is not the one-object
 * contract `ww --json` prints is a failure with the child's first words, never a partial answer.
 */
export function parseRetellOutput(stdout: string): RetellResult {
  let body: JsonObject;
  try {
    const parsed: unknown = JSON.parse(stdout);
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) throw new Error("not an object");
    // SAFETY: a non-null, non-array JSON value is an object whose values are JSON values.
    body = parsed as JsonObject;
  } catch {
    return { ok: false, error: `unreadable retell output: ${stdout.trim().slice(0, 160)}` };
  }
  if (body.ok !== true) {
    return { ok: false, error: typeof body.error === "string" ? body.error : "retell failed" };
  }
  const { sessionId, mode, label, answer, cached, source } = body;
  if (
    typeof sessionId !== "string" ||
    (mode !== "plain" && mode !== "lost") ||
    typeof label !== "string" ||
    typeof answer !== "string" ||
    answer.trim() === "" ||
    typeof cached !== "boolean" ||
    typeof source !== "string"
  ) {
    return { ok: false, error: "retell output is missing a field" };
  }
  return { ok: true, sessionId, mode, label, answer, cached, source };
}

export interface RetellChild {
  readonly exited: Promise<number>;
  readonly stdout: Promise<string>;
  kill(): void;
}

export type RetellSpawn = (argv: readonly string[]) => RetellChild;

/** A retelling of a long session measured at 44s through the local proxy; this bounds a hung one. */
export const RETELL_TIMEOUT_MS = 180_000;

export const bunRetellSpawn: RetellSpawn = (argv) => {
  const child = Bun.spawn([...argv], { stdin: "ignore", stdout: "pipe", stderr: "ignore" });
  return { exited: child.exited, stdout: new Response(child.stdout).text(), kill: () => child.kill() };
};

/** Run one child to its end or the timeout, whichever is first. */
export async function runRetell(
  spawn: RetellSpawn,
  argv: readonly string[],
  expect: { sessionId: string; mode: RetellMode },
  timeoutMs = RETELL_TIMEOUT_MS,
): Promise<RetellResult> {
  let child: RetellChild;
  try {
    child = spawn(argv);
  } catch (err) {
    return { ok: false, error: `could not start ${argv[0] ?? "retell"}: ${String(err)}` };
  }
  let timer: ReturnType<typeof setTimeout> | undefined;
  const timedOut = new Promise<"timeout">((resolve) => {
    timer = setTimeout(() => resolve("timeout"), timeoutMs);
  });
  const done = await Promise.race([Promise.all([child.exited, child.stdout]), timedOut]);
  clearTimeout(timer);
  if (done === "timeout") {
    child.kill();
    return { ok: false, error: `retell took longer than ${Math.round(timeoutMs / 1000)}s` };
  }
  const result = parseRetellOutput(done[1]);
  // A child that answered for another session or mode is refused rather than shown: the sheet must
  // never present one conversation's retelling as another's.
  if (result.ok && (result.sessionId !== expect.sessionId || result.mode !== expect.mode)) {
    return { ok: false, error: "retell answered for a different session" };
  }
  return result;
}
