import type { JsonObject } from "./json.ts";
import { createOperatorFileReader, diskIo, type OperatorFileIo } from "./operator-file.ts";

// "Plain" / "lost" retellings of a Claude session for the phone, generated by the operator's own
// cc-sidecar-waitwhat (`ww`) so the prompts, the turn selection and the answer cache stay the ones
// the terminal and the in-Claude mod already share — Collie writes no prompt of its own.
//
// This is the second exception to "the bridge spawns no child for content" (ADR 0074): it exists
// only while the operator's `retell.toml` names a command, and each request is ONE short-lived child
// with a fixed argv — never a shell, never a daemon, never an argument the phone chose. The phone
// names a pane and one of two modes; the bridge maps the pane to the session id the multiplexer
// reported and adds that id as the child's `--session-id`.

export type RetellMode = "plain" | "lost";

/** The operator's `retell.toml`, parsed. */
export interface RetellConfig {
  /** argv prefix, e.g. `["/Users/me/.local/bin/ww", "--source", "http"]`. */
  readonly command: readonly string[];
}

/**
 * ```toml
 * command = ["/Users/me/.local/bin/ww", "--source", "http"]
 * ```
 *
 * An array, not a shell line: nothing is ever split or interpreted, so no character in it needs
 * escaping and none can smuggle a second command. Returns zero rows or one.
 */
export function validateRetellConfig(
  doc: { command?: unknown } | null | undefined,
  warn = defaultWarn,
): RetellConfig[] {
  const command = doc?.command;
  if (command === undefined || command === null) return [];
  if (!Array.isArray(command) || command.length === 0) {
    warn("`command` must be a non-empty array of strings — retell stays off");
    return [];
  }
  const argv: string[] = [];
  for (const part of command) {
    if (typeof part !== "string" || part === "" || part.includes("\0")) {
      warn("`command` holds a value that is not a non-empty string — retell stays off");
      return [];
    }
    argv.push(part);
  }
  return [{ command: argv }];
}

function defaultWarn(message: string): void {
  console.warn(`[retell] ${message}`);
}

export function createOperatorRetell(
  path: string,
  io: OperatorFileIo = diskIo,
  warn = defaultWarn,
): () => Promise<RetellConfig[]> {
  return createOperatorFileReader(path, validateRetellConfig, io, warn);
}

/** The child's argv for one request. The session id is the multiplexer's, never the client's. */
export function retellArgv(config: RetellConfig, mode: RetellMode, sessionId: string, fresh: boolean): string[] {
  return [
    ...config.command,
    ...(mode === "plain" ? ["1"] : []),
    "--session-id",
    sessionId,
    "--json",
    ...(fresh ? ["--no-cache"] : []),
  ];
}

export type RetellResult =
  | {
      readonly ok: true;
      readonly sessionId: string;
      readonly mode: RetellMode;
      readonly label: string;
      readonly answer: string;
      readonly cached: boolean;
      readonly source: string;
    }
  | { readonly ok: false; readonly error: string };

/**
 * The child's stdout, believed only as far as it checks out. A body that is not the one-object
 * contract `ww --json` prints is a failure with the child's first words, never a partial answer.
 */
export function parseRetellOutput(stdout: string): RetellResult {
  let body: JsonObject;
  try {
    const parsed: unknown = JSON.parse(stdout);
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) throw new Error("not an object");
    // SAFETY: a non-null, non-array JSON value is an object whose values are JSON values.
    body = parsed as JsonObject;
  } catch {
    return { ok: false, error: `unreadable retell output: ${stdout.trim().slice(0, 160)}` };
  }
  if (body.ok !== true) {
    return { ok: false, error: typeof body.error === "string" ? body.error : "retell failed" };
  }
  const { sessionId, mode, label, answer, cached, source } = body;
  if (
    typeof sessionId !== "string" ||
    (mode !== "plain" && mode !== "lost") ||
    typeof label !== "string" ||
    typeof answer !== "string" ||
    answer.trim() === "" ||
    typeof cached !== "boolean" ||
    typeof source !== "string"
  ) {
    return { ok: false, error: "retell output is missing a field" };
  }
  return { ok: true, sessionId, mode, label, answer, cached, source };
}

export interface RetellChild {
  readonly exited: Promise<number>;
  /** Rejects when the child writes more than {@link RETELL_MAX_OUTPUT_BYTES}. */
  readonly stdout: Promise<string>;
  /** Where a sidecar says why it failed. Optional so a stand-in child need not supply one. */
  readonly stderr?: Promise<string>;
  /** No signal is the polite one; 9 is the one a hung child cannot ignore. */
  kill(signal?: number): void;
}

export type RetellSpawn = (argv: readonly string[]) => RetellChild;

/** A retelling of a long session measured at 44s through the local proxy; this bounds a hung one. */
export const RETELL_TIMEOUT_MS = 180_000;
/** How long a child asked to stop may take before it is killed outright. */
export const RETELL_KILL_GRACE_MS = 2_000;
/** A retelling is a few paragraphs; anything this large is not one, and is not held in memory. */
export const RETELL_MAX_OUTPUT_BYTES = 1024 * 1024;
/** How much of the child's own words a failure carries to the phone. */
const RETELL_REASON_CHARS = 300;

/** A stream read to its end, or rejected once it passes `max` bytes. */
async function readCapped(stream: ReadableStream<Uint8Array>, max: number): Promise<string> {
  const chunks: Uint8Array[] = [];
  let size = 0;
  for await (const chunk of stream) {
    size += chunk.byteLength;
    if (size > max) throw new Error(`output over ${max} bytes`);
    chunks.push(chunk);
  }
  return new TextDecoder().decode(Buffer.concat(chunks));
}

export const bunRetellSpawn: RetellSpawn = (argv) => {
  const child = Bun.spawn([...argv], { stdin: "ignore", stdout: "pipe", stderr: "pipe" });
  return {
    exited: child.exited,
    stdout: readCapped(child.stdout, RETELL_MAX_OUTPUT_BYTES),
    stderr: readCapped(child.stderr, RETELL_MAX_OUTPUT_BYTES).catch(() => ""),
    kill: (signal) => child.kill(signal),
  };
};

/** The child's own reason, on one line and bounded: its stderr first, else what it printed. */
function childReason(stderr: string, stdout: string): string {
  const text = (stderr.trim() || stdout.trim()).replace(/\s+/g, " ");
  return text.slice(0, RETELL_REASON_CHARS);
}

/** Run one child to its end or the timeout, whichever is first. */
export async function runRetell(
  spawn: RetellSpawn,
  argv: readonly string[],
  expect: { sessionId: string; mode: RetellMode },
  timeoutMs = RETELL_TIMEOUT_MS,
  graceMs = RETELL_KILL_GRACE_MS,
): Promise<RetellResult> {
  let child: RetellChild;
  try {
    child = spawn(argv);
  } catch (err) {
    return { ok: false, error: `could not start ${argv[0] ?? "retell"}: ${String(err)}` };
  }
  let timer: ReturnType<typeof setTimeout> | undefined;
  const timedOut = new Promise<"timeout">((resolve) => {
    timer = setTimeout(() => resolve("timeout"), timeoutMs);
  });
  let done: [number, string, string] | "timeout";
  try {
    done = await Promise.race([Promise.all([child.exited, child.stdout, child.stderr ?? Promise.resolve("")]), timedOut]);
  } catch (err) {
    clearTimeout(timer);
    child.kill(9);
    return { ok: false, error: `unreadable retell output: ${err instanceof Error ? err.message : String(err)}` };
  }
  clearTimeout(timer);
  if (done === "timeout") {
    child.kill();
    // A kill is a request; wait a moment for the exit, then make it one it cannot refuse.
    let grace: ReturnType<typeof setTimeout> | undefined;
    const stopped = await Promise.race([
      child.exited.then(() => true),
      new Promise<boolean>((resolve) => {
        grace = setTimeout(() => resolve(false), graceMs);
      }),
    ]);
    clearTimeout(grace);
    if (!stopped) child.kill(9);
    return { ok: false, error: `retell took longer than ${Math.round(timeoutMs / 1000)}s` };
  }
  const [code, stdout, stderr] = done;
  // A non-zero exit is a failure whatever it printed: a body that happens to parse is not an answer
  // the sidecar stood behind.
  if (code !== 0) {
    const reason = childReason(stderr, stdout);
    return { ok: false, error: reason === "" ? `retell exited with status ${code}` : `retell exited with status ${code}: ${reason}` };
  }
  const result = parseRetellOutput(stdout);
  // A child that answered for another session or mode is refused rather than shown: the sheet must
  // never present one conversation's retelling as another's.
  if (result.ok && (result.sessionId !== expect.sessionId || result.mode !== expect.mode)) {
    return { ok: false, error: "retell answered for a different session" };
  }
  return result;
}
